[package]
name = "rust-serverless-lambda"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["examples/*"]
resolver = "2"

[workspace.dependencies]
lambda_http = "0.14.0"
tokio = "1"
tracing = "0.1.41"
lambda_runtime = "0.13.0"